#!/usr/bin/env python
# coding: utf-8

"""
Authors: Zoe Batterman and Chris Yao

Combines the raw data generated by Eigenvalues_of_Matrices.nb into parsable csv's
"""

import numpy
import os
from os import listdir
import pandas as pd
from statistics import mean

import matplotlib.pyplot as plt
import seaborn as sns
from math import pi, log

if __name__ == "__main__":
    raw_path = r"C:\Users\Chris.CHRIS-SPECTRE\Documents"
    data_path = r"data/rmt"
    data_type = "Random_SO19_Data"

    all_df = []

    for csv_path in [file for file in listdir(raw_path) if data_type in file and "csv" in file]:
        all_df.append(pd.read_csv(f"{raw_path}/{csv_path}", names=["lowest", "charpoly"]))

    result = pd.concat(all_df)
    result.to_csv(f"{data_path}/{data_type}.csv", index=False)
